import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navlinks: { name: string; href: string }[] = [
  { name: "Completion", href: "/ui/completion" },
  { name: "Stream", href: "/ui/stream" },
  { name: "Chat", href: "/ui/chat" },
  { name: "System Prompt", href: "/ui/system-prompt" },
  { name: "Structured Data", href: "/ui/structured-data" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex items-center justify-center gap-8 p-4 border-b border-zinc-200 dark:border-zinc-800 mb-8">
            {navlinks.map((link) => (
              <li key={link.href}>
                <Link href={link.href}>{link.name}</Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
