import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navlinks: { name: string; href: string }[] = [
  { name: "Completion", href: "/ui/completion" },
  { name: "Stream", href: "/ui/stream" },
  { name: "Chat", href: "/ui/chat" },
  { name: "System Prompt", href: "/ui/system-prompt" },
  { name: "Structured Data", href: "/ui/structured-data" },
  { name: "Structured Array", href: "/ui/structured-array" },
  { name: "Structured Enum", href: "/ui/structured-enum" },
  { name: "Multi-Modal Chat", href: "/ui/multi-modal-chat" },
  { name: "Generate Image", href: "/ui/generate-image" },
  { name: "Transcribe Audio", href: "/ui/transcribe-audio" },
  { name: "Generate Speech", href: "/ui/generate-speech" },
  { name: "Tools Chat", href: "/ui/tools" },
  { name: "Multiple Tools Chat", href: "/ui/multiple-tools" },
  { name: "API Tool Chat", href: "/ui/api-tool" },
  { name: "Web Search Tool", href: "/ui/web-search-tool" },
  { name: "Generate Image Tool", href: "/ui/generate-image-tool" },
  { name: "Client Side Tools", href: "/ui/client-side-tools" },
  { name: "Mcp Tools Chat", href: "/ui/mcp-tools" },
  { name: "Reasoning Chat", href: "/ui/reasoning" },
  { name: "Message Metadata", href: "/ui/message-metadata" },
  { name: "Provider Management", href: "/ui/provider-management" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex items-center justify-center gap-8 p-4 border-b border-zinc-200 dark:border-zinc-800 mb-8 flex-wrap">
            {navlinks.map((link) => (
              <li key={link.href}>
                <Link href={link.href}>{link.name}</Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
